export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };

  export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

    USER_SIGNUP_AUTHENTICATION_REQUEST: "USER_SIGNUP_AUTHENTICATION_REQUEST",
    USER_SIGNUP_AUTHENTICATION_SUCCESS: "USER_SIGNUP_AUTHENTICATION_SUCCESS",
    USER_SIGNUP_AUTHENTICATION_FAILURE: "USER_SIGNUP_AUTHENTICATION_FAILURE",

    GET_USER_BY_FIRSTNAME_REQUEST:"GET_USER_BY_FIRSTNAME_REQUEST",
    GET_USER_BY_FIRSTNAME_SUCCESS:"GET_USER_BY_FIRSTNAME_SUCCESS",
    GET_USER_BY_FIRSTNAME_FAILURE:"GET_USER_BY_FIRSTNAME_FAILURE",

    GET_USER_BY_USERNAME_REQUEST:"GET_USER_BY_USERNAME_REQUEST",
    GET_USER_BY_USERNAME_SUCCESS:"GET_USER_BY_USERNAME_SUCCESS",
    GET_USER_BY_USERNAME_FAILURE:"GET_USER_BY_USERNAME_FAILURE",

    UPDATE_USER_PROFILE_REQUEST:"UPDATE_USER_PROFILE_REQUEST",
    UPDATE_USER_PROFILE_SUCCESS:"UPDATE_USER_PROFILE_SUCCESS",
    UPDATE_USER_PROFILE_FAILURE:"UPDATE_USER_PROFILE_FAILURE",

    UPDATE_USER_PROFILE_PICTURE_REQUEST:"UPDATE_USER_PROFILE_PICTURE_REQUEST",
    UPDATE_USER_PROFILE_PICTURE_SUCCESS:"UPDATE_USER_PROFILE_PICTURE_SUCCESS",
    UPDATE_USER_PROFILE_PICTURE_FAILURE:"UPDATE_USER_PROFILE_PICTURE_FAILURE",

    UPDATE_USER_COVER_PICTURE_REQUEST:"UPDATE_USER_COVER_PICTURE_REQUEST",
    UPDATE_USER_COVER_PICTURE_SUCCESS:"UPDATE_USER_COVER_PICTURE_SUCCESS",
    UPDATE_USER_COVER_PICTURE_FAILURE:"UPDATE_USER_COVER_PICTURE_FAILURE",

    ADD_USER_PUBLICITY_REQUEST:"ADD_USER_PUBLICITY_REQUEST",
    ADD_USER_PUBLICITY_SUCCESS:"ADD_USER_PUBLICITY_SUCCESS",
    ADD_USER_PUBLICITY_FAILURE:"ADD_USER_PUBLICITY_FAILURE",

    REMOVE_USER_PUBLICITY_REQUEST:"REMOVE_USER_PUBLICITY_REQUEST",
    REMOVE_USER_PUBLICITY_SUCCESS:"REMOVE_USER_PUBLICITY_SUCCESS",
    REMOVE_USER_PUBLICITY_FAILURE:"REMOVE_USER_PUBLICITY_FAILURE",
  }

  export const postConstants = {
    CREATE_POST_REQUEST:"CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS:"CREATE_POST_SUCCESS",
    CREATE_POST_FAILURE:"CREATE_POST_FAILURE",

    GET_ALL_POST_REQUEST: 'GET_ALL_POST_REQUEST',
    GET_ALL_POST_SUCCESS: 'GET_ALL_POST_SUCCESS',
    GET_ALL_POST_FAILURE: 'GET_ALL_POST_FAILURE',

    GET_ALL_USER_POST_REQUEST: 'GET_ALL_USER_POST_REQUEST',
    GET_ALL_USER_POST_SUCCESS: 'GET_ALL_USER_POST_SUCCESS',
    GET_ALL_USER_POST_FAILURE: 'GET_ALL_USER_POST_FAILURE',

    DELETE_POST_BY_ID_REQUEST: "DELETE_POST_BY_ID_REQUEST",
    DELETE_POST_BY_ID_SUCCESS: "DELETE_POST_BY_ID_SUCCESS",
    DELETE_POST_BY_ID_FAILURE: "DELETE_POST_BY_ID_FAILURE",

    UPDATE_POST_BY_ID_REQUEST: "UPDATE_POST_BY_ID_REQUEST",
    UPDATE_POST_BY_ID_SUCCESS: "UPDATE_POST_BY_ID_SUCCESS",
    UPDATE_POST_BY_ID_FAILURE: "UPDATE_POST_BY_ID_FAILURE",

    EDIT_POST_BY_ID_REQUEST: "EDIT_POST_BY_ID_REQUEST",
    EDIT_POST_BY_ID_SUCCESS: "EDIT_POST_BY_ID_SUCCESS",
    EDIT_POST_BY_ID_FAILURE: "EDIT_POST_BY_ID_FAILURE",

}

